# Generated by Django 3.0.7 on 2021-01-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boopay',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=25)),
                ('menu', models.CharField(max_length=25)),
                ('bid', models.IntegerField()),
                ('start', models.DateField()),
                ('area_code', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('subject', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=2)),
                ('card', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('num', models.CharField(max_length=16)),
                ('cvv', models.IntegerField(max_length=4)),
                ('date', models.DateField()),
                ('price', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=25)),
                ('menu', models.CharField(max_length=25)),
                ('bid', models.CharField(max_length=50)),
                ('start', models.CharField(max_length=25)),
                ('area_code', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=25)),
                ('Facility', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=2)),
                ('Purpose', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Living',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('1', 'premium'), ('2', 'deluxe'), ('3', 'basic')], max_length=50)),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'available'), ('2', 'not available')], max_length=15)),
                ('roomnumber', models.CharField(default=12, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('m_name', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('menu_type', models.CharField(blank=True, max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password1', models.CharField(max_length=15)),
                ('password2', models.CharField(max_length=15)),
                ('phone_no', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=5)),
                ('age', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('booking_id', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
